config/routes.rb
Rails.application.routes.draw do

  namespace :tab do
    get "wand"
  end
  namespace :board do
    get "mirror"
    get "wireframe2"
    get "wireframe3"
    get "wireframe4"
  end
  
  namespace :magic do
    get "home"
    get "sensing"
    get "gestures"
    get "light"
    get "mirror_portal"
    get "wand_portal"
    get "mirrorInteraction"
    get "wandInteraction"
    get "remoteInteraction"
  end

  root 'application#index'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def index
    
  end
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  def mirror
  end

  def wireframe2
  end
  
  def wireframe3
  end

  def wireframe4
  end

end



        # @images = {}
        # @images["/wireframe1.png"] = ["/wireframe2.png",
        #   "/wireframe2.png"]
        # @images["/wireframe2.png"] = ["/wireframe3.png",
        #   "/wireframe3.png"]
        # @images["/wireframe3.png"] = ["/wireframe4.png",
        #   "/v1_screens/4_0.jpg"]
    
        # puts @images
        
        # if !params[:image].nil?
        #   @image = params[:image]
        #   @image_next = @images[@image][0]
        # else
        #   @image = '/wireframe1.png'
        #   redirect_to v1_home_path(:image => @image)
        # end

app/controllers/magic_controller.rb
class MagicController < ApplicationController
  def home
  end
  
  def orientation
  end
  
  def gestures
  end
  
  def light
  end
  
  def portal
  end
  
  def mirrorInteraction
  end
  
  def wandInteraction
  end
  
  def remoteInteraction
  end
  
end

app/controllers/tab_controller.rb
class TabController < ApplicationController
  def wand
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/magic_helper.rb
module MagicHelper
end

app/helpers/tab_helper.rb
module TabHelper
end

app/views/application/_back_to_root.html.haml
:scss
    #back-button{
        position: absolute;
        z-index: 100;
        top: 15px;
        left: 15px;
    }
    
= link_to root_path, id: "back-button", class: "btn btn-primary" do
    %span.glyphicon.glyphicon-chevron-left

app/views/application/index.html.haml
.container-fluid.np
    .col-xs-12.col-sm-6.np
        .panel.panel-primary
            .panel-heading 
                %b
                    Practicum 4
                Mirror, mirror
            .panel-body
                %ul.list-group
                    %li.list-group-item 
                        = link_to magic_sensing_path do
                            %b #1
                            Orientation and Motion APIs
                            %span.pull-right.glyphicon.glyphicon-chevron-right
                    %li.list-group-item 
                        = link_to magic_gestures_path do
                            %b #2
                            Gesture Recognizer
                            %span.pull-right.glyphicon.glyphicon-chevron-right
                    %li.list-group-item 
                        = link_to magic_light_path do
                            %b #3
                            Light Detector
                            %span.pull-right.glyphicon.glyphicon-chevron-right
                    %li.list-group-item 
                        = link_to magic_mirror_portal_path do
                            %b #4
                            Portal - Mirror
                            %span.pull-right.glyphicon.glyphicon-chevron-right
                    %li.list-group-item 
                        = link_to magic_wand_portal_path do
                            %b #4
                            Portal - Wand
                            %span.pull-right.glyphicon.glyphicon-chevron-right
                    %li.list-group-item 
                        = link_to board_mirror_path do
                            %b #5
                            Magic Mirror UI
                            %span.pull-right.glyphicon.glyphicon-chevron-right
                    %li.list-group-item 
                        = link_to tab_wand_path do
                            %b #6
                            Magic Wand UI
                            %span.pull-right.glyphicon.glyphicon-chevron-right
                   
            .panel-footer
                CS160 - Intro to UI Design and Development
   

app/views/board/mirror.html.haml
#container
    %a{href: "/board/wireframe2"}
        %img{src: "/wireframe1.png", width: "28%"}

// @images = {}
//         @images["/wireframe1.png"] = ["/wireframe2.png",
//           "/wireframe2.png"]
//         @images["/wireframe2.png"] = ["/wireframe3.png",
//           "/wireframe3.png"]
//         @images["/wireframe3.png"] = ["/wireframe4.png",
//           "/v1_screens/4_0.jpg"]
    
//         puts @images


// // IGNORE, BUT KEEP THIS LINE (Back button)   
// = render :partial => "application/back_to_root"



// #mirror
//     #webcam-feed.col-xs-12
//         %span MIRROR, MIRROR
      
// // IGNORE, BUT KEEP THIS LINE (Back button)   
// = render :partial => "application/back_to_root"

// :scss
//     #mirror{
//         height: 100%;
//         width: 100%;
//         color: white;
//         font-family: Avenir, sans-serif;
//         font-size: 4em;
//         text-align: center;
            
//         #webcam-feed{
//             height: 100%;
//             background: desaturate(blue, 80%);
//             display: flex;
//             justify-content: center;
//             align-items: center;
//             flex-direction: column;
//         }
       
//     }
   

app/views/board/wireframe2.html.haml
#container
    %a{href: "/board/wireframe3"}
        %img{src: "/wireframe2.png", width: "28%"}

// @images = {}
//         @images["/wireframe1.png"] = ["/wireframe2.png",
//           "/wireframe2.png"]
//         @images["/wireframe2.png"] = ["/wireframe3.png",
//           "/wireframe3.png"]
//         @images["/wireframe3.png"] = ["/wireframe4.png",
//           "/v1_screens/4_0.jpg"]
    
//         puts @images


// // IGNORE, BUT KEEP THIS LINE (Back button)   
// = render :partial => "application/back_to_root"



// #mirror
//     #webcam-feed.col-xs-12
//         %span MIRROR, MIRROR
      
// // IGNORE, BUT KEEP THIS LINE (Back button)   
// = render :partial => "application/back_to_root"

// :scss
//     #mirror{
//         height: 100%;
//         width: 100%;
//         color: white;
//         font-family: Avenir, sans-serif;
//         font-size: 4em;
//         text-align: center;
            
//         #webcam-feed{
//             height: 100%;
//             background: desaturate(blue, 80%);
//             display: flex;
//             justify-content: center;
//             align-items: center;
//             flex-direction: column;
//         }
       
//     }
   

app/views/board/wireframe3.html.haml
#container
    %a{href: "/board/wireframe4"}
        %img{src: "/wireframe3.png", width: "28%"}

// @images = {}
//         @images["/wireframe1.png"] = ["/wireframe2.png",
//           "/wireframe2.png"]
//         @images["/wireframe2.png"] = ["/wireframe3.png",
//           "/wireframe3.png"]
//         @images["/wireframe3.png"] = ["/wireframe4.png",
//           "/v1_screens/4_0.jpg"]
    
//         puts @images


// // IGNORE, BUT KEEP THIS LINE (Back button)   
// = render :partial => "application/back_to_root"



// #mirror
//     #webcam-feed.col-xs-12
//         %span MIRROR, MIRROR
      
// // IGNORE, BUT KEEP THIS LINE (Back button)   
// = render :partial => "application/back_to_root"

// :scss
//     #mirror{
//         height: 100%;
//         width: 100%;
//         color: white;
//         font-family: Avenir, sans-serif;
//         font-size: 4em;
//         text-align: center;
            
//         #webcam-feed{
//             height: 100%;
//             background: desaturate(blue, 80%);
//             display: flex;
//             justify-content: center;
//             align-items: center;
//             flex-direction: column;
//         }
       
//     }
   

app/views/board/wireframe4.html.haml
#container
    %a{href: "/board/mirror"}
        %img{src: "/wireframe4.png", width: "28%"}

// @images = {}
//         @images["/wireframe1.png"] = ["/wireframe2.png",
//           "/wireframe2.png"]
//         @images["/wireframe2.png"] = ["/wireframe3.png",
//           "/wireframe3.png"]
//         @images["/wireframe3.png"] = ["/wireframe4.png",
//           "/v1_screens/4_0.jpg"]
    
//         puts @images


// // IGNORE, BUT KEEP THIS LINE (Back button)   
// = render :partial => "application/back_to_root"



// #mirror
//     #webcam-feed.col-xs-12
//         %span MIRROR, MIRROR
      
// // IGNORE, BUT KEEP THIS LINE (Back button)   
// = render :partial => "application/back_to_root"

// :scss
//     #mirror{
//         height: 100%;
//         width: 100%;
//         color: white;
//         font-family: Avenir, sans-serif;
//         font-size: 4em;
//         text-align: center;
            
//         #webcam-feed{
//             height: 100%;
//             background: desaturate(blue, 80%);
//             display: flex;
//             justify-content: center;
//             align-items: center;
//             flex-direction: column;
//         }
       
//     }
   

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Workspace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    - controller = params[:controller]
    - if controller != 'application'
      = stylesheet_link_tag    controller, media: 'all', 'data-turbolinks-track' => true
      = javascript_include_tag controller, 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{name:"viewport", content: "user-scalable=no, width=device-width, initial-scale=1"}

  %body
    = yield

app/views/magic/gestures.html.haml
:coffeescript
    $ ->
        console.log "BIND VALUES FROM APIS TO VIEW ELEMENTS HERE"
        console.log "DETECT AN UP, DOWN, LEFT, RIGHT, FORWARD, BACK gesture"

        

#gesturepad
    #gesture-square
        #screen
    %h1#gesture &lt;&lt;GESTURE DETECTED&gt;&gt;
    %h2#orientation ATTACH GYROSCOPE DATA TO ME
    %h3#acceleration ATTACH ACCELEROMETER DATA TO ME

    
// IGNORE, BUT KEEP THIS LINE (Back button)   
= render :partial => "application/back_to_root"
    
:scss
    $gesturepad-bg: desaturate(green, 70%);
    $gesture-square: lighten($gesturepad-bg, 70%);
    html, body{ overflow: none;}
    #gesturepad{
        height: 100%;
        width: 100%;
        overflow: none;
        color: white;
        font-family: Avenir, sans-serif;
        font-size: 4em;
        text-align: center;
            
        background: $gesturepad-bg;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        #gesture-square{
            width: 150px;
            height: 200px;
            background: $gesture-square;
            transition: transform 2s;
            #screen{
                width: calc(100% - 20px);
                height: calc(100% - 30px);
                background: darken($gesture-square, 80%);
                margin: 10px;
                margin-bottom: 20px;
            }
        }
    }
    

app/views/magic/home.html.haml
%h1 Magic#home
%p Find me in app/views/magic/home.html.haml

app/views/magic/light.html.haml
:coffeescript
    $ ->
        video = document.getElementById('video')
        if navigator.mediaDevices and navigator.mediaDevices.getUserMedia
            navigator.mediaDevices.getUserMedia(video: true).then (stream) ->
                video.src = window.URL.createObjectURL(stream)
                video.play()
                return
            
        canvas = document.getElementById('canvas')
        context = canvas.getContext('2d')
        video = document.getElementById('video')
        #document.getElementById('snap').addEventListener 'click', ->
        poll = ->
            nIntervId = setInterval(getData, 500)
            return
        lightArray = []
        getData = ->
            context.drawImage video, 0, 0, 320, 240
            pixel = context.getImageData(0, 0, 320, 240)
            imgData = pixel.data
            i = 0
            count = 0
            BRIGHTNESS = 0
            while i < imgData.length - 4
                R = imgData[i]
                G = imgData[i+1]
                B = imgData[i+2]
                A = imgData[i+3]
                BRIGHTNESS += (0.2126 * R + 0.7152 * G + 0.0722 * B)
                i += 4
                count++
            light = BRIGHTNESS/count
            document.getElementById('avg').innerHTML = light
            lightArray.push light
            if lightArray.length > 3
                lightArray.shift()
            if lightArray[2] - lightArray[0] > 25
                document.getElementById('lights').innerHTML = "EVENT: LIGHTS TURNED ON"
            else if lightArray[0] - lightArray[2] > 25
                document.getElementById('lights').innerHTML = "EVENT: LIGHTS TURNED OFF"
            else if light > 40
                document.getElementById('lights').innerHTML = "EVENT: LIGHTS ON"
            else
                document.getElementById('lights').innerHTML = "EVENT: LIGHTS OFF"
            return
        poll()

#instadesktop
    #webcam-feed.col-xs-12.col-sm-6
        %span
            %video#video{:autoplay => "", :height => "360", :width => "480"}
        %canvas#canvas{:height => "240", :width => "320"}

    #snapshot.col-xs-12.col-sm-6
        %h1#lights 
        %h2#avg

// IGNORE, BUT KEEP THIS LINE (Back button)   
= render :partial => "application/back_to_root"
:scss
    #instadesktop{
        height: 100%;
        width: 100%;
        color: white;
        font-family: Avenir, sans-serif;
        font-size: 4em;
        text-align: center;
            
        #canvas {
            opacity: 0;
            height: 35px;
            width: 35px;
        }
        
        #webcam-feed{
            height: 100%;
            background: desaturate(blue, 80%);
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            button{
                position: absolute;
                bottom: 0;
            }
        }
        #snapshot{
            height: 100%;
            background: desaturate(red, 80%);
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            position: relative;
        }
    }
    #back-button{
        position: absolute;
        z-index: 100;
        top: 15px;
        left: 15px;
    }

app/views/magic/mirrorInteraction.html.haml
:coffeescript
    $ ->
        video = document.getElementById('video')
        if navigator.mediaDevices and navigator.mediaDevices.getUserMedia
            navigator.mediaDevices.getUserMedia(video: true).then (stream) ->
                video.src = window.URL.createObjectURL(stream)
                video.play()
                return
        $('#video').css
            width: $(window).innerWidth() + 'px'
            height: $(window).innerHeight() + 'px'
        vid = document.getElementById('myVideo')
                
        connection = new WebSocket('wss://p4-cs160-samy-jerry-jerrywu17.c9users.io:8081')

        connection.onopen = ->
            console.log "this is being opened"
            $("#status").html("&#9679 CONNECTED")
            $('#status').removeClass('red').addClass 'green'
        
        connection.onclose = ->
            console.log "this is being closed"
            $("#status").html("&#9679 NOT CONNECTED")
            $('#status').removeClass('green').addClass 'red'

        
        connection.onmessage = (event) ->
            
            if _.isString(event.data)
                #create a JSON object
                jsonObject = JSON.parse(event.data)
                username = jsonObject.identity
                message = jsonObject.message
                
                
                if message == "play"
                    console.log "receive play message"
                    vid.play()
                if message == "pause"
                    console.log "receive pause message"
                    vid.pause()
                if message == "rewind"
                    console.log "receive rewind message"
                    if vid.currentTime <= 15
                        vid.currentTime = 0
                    else
                        vid.currentTime -= 15;
                if message == "forward"
                    console.log "receive forward message"
                    if vid.currentTime >= vid.duration - 15
                        vid.currentTime = vid.duration
                    else
                        vid.currentTime += 15;
    $ ->
        div = $('#help')
        div.animate {
            right: '+=217'
            opacity: '0.6'
        }, 2000, ->
        div.animate { opacity: '0.8' }, 5000, ->
        div.animate {
            right: '-=230'
            opacity: '0.6'
        }, 2000, ->
        return

#webcam
    %span
        %video#video{:autoplay => ""}
        %video#myVideo{ :height => "176", :width => "320"}
            %source{:src => "https://preview.c9users.io/jerrywu17/p4_cs160_samy_jerry/public/makeup.mp4", :type => "video/mp4"}
        #status.red
            &#9679 NOT CONNECTED
        #help
            =image_tag "https://preview.c9users.io/jerrywu17/p4_cs160_samy_jerry/public/help.png", :class => "image"
            .text
                %br
                To 
                play video, 
                %b lean forward.
                %br
                To 
                pause,
                %b lean back.
                %br
                To 
                rewind,
                %b roll wand left.
                %br
                To 
                forward,
                %b roll wand right.
                
        


    
    
:scss
    html, body{ overflow: none;}
    #webcam{
        height: 100%;
        width: 100%;
    }
    #myVideo{
        position: absolute;
        top: 0px;
        right: 0px;
    }
    #video {
        height: 100%;
        width: 100%;
        object-fit: cover;
     }
    #button{
        background: white;
        width: 180px;
        height: 40px;
        font-size: 18pt;
        text-align: center;
        border-style: solid;
        border-width: 3px;
        border-color: green;
        border-radius: 15px;
    }
    #status{
        position: absolute;
        bottom: 10px;
        right: 10px;
        font-size: 10pt;
        font-weight: bold;
    }
    .red{
        color: red;
    }
    .green{
        color: #39e550;
    }
    #help{
        position: absolute;
        height: 200px;
        bottom: 50px;
        right: -217px;
        border-radius: 30px 0px 0px 30px;
        background-color: white;
        padding: 20px;
        .text{
            line-height: 1.5;
        }
        .image{
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
    }
    

app/views/magic/mirror_portal.html.haml
:coffeescript
    $ ->
        console.log "WEBSOCKET TO MIRROR HERE"
        console.log "WEBSOCKET HANDLER FROM MIRROR HERE"
                
        connection = new WebSocket('wss://p4-cs160-samy-jerry-jerrywu17.c9users.io:8081')
        #connection = new WebSocket('wss://www.websocket.org/echo.html')

        connection.onopen = ->
            connection.send JSON.stringify {message: "Hello", identity: "mirror"}
            console.log "this is being opened"
        
        $('#button').click (event) ->

            #display the current click count inside the clicked div
            connection.send(JSON.stringify({
                   identity: "mirror",
                   message: "Hello wand"
               })
            )
        
        
        numTimes = ""

        connection.onmessage = (event) ->
            console.log("*******on message: MIRROR")
            
            if _.isString(event.data)
                jsonObject = JSON.parse(event.data)
                username = jsonObject.identity
                message = jsonObject.message
                
                console.log("username: " + username)

                if username == "wand"
                    $("#message-mirror").html(message + numTimes)
                    numTimes = numTimes + "!"

                    console.log("Received data string from wand")

        # let the receiver store the number of exclamation marks

        

#wand
    %h1#message-mirror I am the mirror
    #button
        Press me!
    
// IGNORE, BUT KEEP THIS LINE (Back button)   
= render :partial => "application/back_to_root"
    
:scss
    $bg: desaturate(purple, 70%);
    html, body{ overflow: none;}
    #wand{
        height: 100%;
        width: 100%;
        overflow: none;
        color: white;
        font-family: Avenir, sans-serif;
        font-size: 4em;
        text-align: center;
            
        background: $bg;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
    }
    #button{
        background: white;
        color: $bg;
        width: 180px;
        height: 40px;
        font-size: 18pt;
        text-align: center;
        border-style: solid;
        border-width: 3px;
        border-color: green;
        border-radius: 15px;
    }
    

app/views/magic/remoteInteraction.haml
:coffeescript
    $ ->
        console.log "WEBSOCKET TO MIRROR HERE"
        console.log "WEBSOCKET HANDLER FROM MIRROR HERE"
                
        connection = new WebSocket('wss://p4-cs160-samy-jerry-jerrywu17.c9users.io:8081')

        connection.onopen = ->
            console.log "this is being opened"
        
        
        $('#play').click (event) ->
            connection.send(JSON.stringify({
                   identity: "wand",
                   message: "play"
               })
            )
         $('#pause').click (event) ->
            connection.send(JSON.stringify({
                   identity: "wand",
                   message: "pause"
               })
            )
        $('#rewind').click (event) ->
            connection.send(JSON.stringify({
                   identity: "wand",
                   message: "rewind"
               })
            )
        $('#forward').click (event) ->
            connection.send(JSON.stringify({
                   identity: "wand",
                   message: "forward"
               })
            )
        
        
#wand
    #play.button Play Video
    #pause.button Pause Video
    #rewind.button Rewind Video
    #forward.button Forward Video

    

    
:scss
    $bg: desaturate(purple, 20%);
    html, body{ overflow: none;}
    #wand{
        height: 100%;
        width: 100%;
        overflow: none;
        color: white;
        font-family: Avenir, sans-serif;
        font-size: 4em;
        text-align: center;
            
        background: $bg;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
    }

    .button{
        background: white;
        color: desaturate($bg, 20%);
        width: 220px;
        height: 70px;
        margin: 10px;
        font-size: 22pt;
        text-align: center;
        border-style: solid;
        border-width: 3px;
        border-color: desaturate($bg, 80%);
        border-radius: 15px;
    }

app/views/magic/sensing.html.haml
:coffeescript
    $ ->


#gesturepad
    #gesture-square
        #screen
    %h2#orientation 
    %h3#acceleration 

    
// IGNORE, BUT KEEP THIS LINE (Back button)   
= render :partial => "application/back_to_root"
    
:scss
    $gesturepad-bg: desaturate(green, 70%);
    $gesture-square: lighten($gesturepad-bg, 70%);
    html, body{ overflow: none;}
    #gesturepad{
        height: 100%;
        width: 100%;
        overflow: none;
        color: white;
        font-family: Avenir, sans-serif;
        font-size: 4em;
        text-align: center;
            
        background: $gesturepad-bg;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        #gesture-square{
            width: 150px;
            height: 200px;
            background: $gesture-square;
            transition: transform 2s;
            #screen{
                width: calc(100% - 20px);
                height: calc(100% - 30px);
                background: darken($gesture-square, 80%);
                margin: 10px;
                margin-bottom: 20px;
            }
        }
    }
    

app/views/magic/wandInteraction.haml
:coffeescript
    $ ->
        console.log "WEBSOCKET TO MIRROR HERE"
        console.log "WEBSOCKET HANDLER FROM MIRROR HERE"
                
        connection = new WebSocket('wss://p4-cs160-samy-jerry-jerrywu17.c9users.io:8081')
        wait = (ms) ->
            start = (new Date).getTime()
            end = start
            while end < start + ms
                end = (new Date).getTime()
            return
        connection.onopen = ->
            console.log "this is being opened"
        lastClicked = ""    
        console.log $('#event').html()
        $('body').on 'DOMSubtreeModified', '#event', ->
            console.log $('#event').html()
            if $('#event').html() == "play"
                lastClicked = "play"
                $('#controlbutton').html('<img src=\'https://preview.c9users.io/jerrywu17/p4_cs160_samy_jerry/public/play.png\'>')
                connection.send(JSON.stringify({
                      identity: "wand",
                      message: "play"
                  })
                )
                wait(80)
            if $('#event').html() == "pause"
                lastClicked = "pause"
                $('#controlbutton').html('<img src=\'https://preview.c9users.io/jerrywu17/p4_cs160_samy_jerry/public/pause.png\'>')
                connection.send(JSON.stringify({
                      identity: "wand",
                      message: "pause"
                  })
                )
                wait(80)
            if $('#event').html() == "rewind"
                lastClicked = "rewind"
                $('#controlbutton').html('<img src=\'https://preview.c9users.io/jerrywu17/p4_cs160_samy_jerry/public/rewind.png\'>')
                connection.send(JSON.stringify({
                      identity: "wand",
                      message: "rewind"
                  })
                )
                wait(80)
            if $('#event').html() == "forward"
                lastClicked = "forward"
                $('#controlbutton').html('<img src=\'https://preview.c9users.io/jerrywu17/p4_cs160_samy_jerry/public/forward.png\'>')
                connection.send(JSON.stringify({
                      identity: "wand",
                      message: "forward"
                    })
                )
                wait(80)
                

                        
        
#wand
    #controlbutton
        //=image_tag "https://preview.c9users.io/jerrywu17/p4_cs160_samy_jerry/public/play.png"
    #event
        play
    // #pause.button Pause Video
    // #rewind.button Rewind Video
    // #forward.button Forward Video

    

    
:scss
    $bg: #f44277;
    html, body{ overflow: none;}
    #wand{
        height: 100%;
        width: 100%;
        overflow: none;
        color: white;
        font-family: Avenir, sans-serif;
        font-size: 4em;
        text-align: center;
            
        background: $bg;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
    }
    #event{
        opacity: 0;
    }

 

app/views/magic/wand_portal.haml
:coffeescript
    $ ->
        console.log "WEBSOCKET TO MIRROR HERE"
        console.log "WEBSOCKET HANDLER FROM MIRROR HERE"
                
        connection = new WebSocket('wss://p4-cs160-samy-jerry-jerrywu17.c9users.io:8081')
        #connection = new WebSocket('wss://www.websocket.org/echo.html')

        connection.onopen = ->
            console.log "this is being opened"
        
        
        $('#button').click (event) ->

            #display the current click count inside the clicked div
            connection.send(JSON.stringify({
                   identity: "wand",
                   message: "Hello mirror"
               })
            )
        
        numTimes = ""

        connection.onmessage = (event) ->
            console.log("*******on message: MIRROR")
            
            if _.isString(event.data)
                #create a JSON object
                jsonObject = JSON.parse(event.data)
                username = jsonObject.identity
                message = jsonObject.message
                
                console.log("username: " + username)
                
                if username == "mirror"
                    $("#message-wand").html(message + numTimes)
                    numTimes = numTimes + "!"

                    console.log("Received data string from mirror", event.data)

        # let the receiver store the number of exclamation marks

        
#wand
    %h1#message-wand I am the wand
    #button Press me!

    
// IGNORE, BUT KEEP THIS LINE (Back button)   
= render :partial => "application/back_to_root"
    
:scss
    $bg: desaturate(purple, 70%);
    html, body{ overflow: none;}
    #wand{
        height: 100%;
        width: 100%;
        overflow: none;
        color: white;
        font-family: Avenir, sans-serif;
        font-size: 4em;
        text-align: center;
            
        background: $bg;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
    }

    #button{
        background: white;
        color: $bg;
        width: 180px;
        height: 40px;
        font-size: 18pt;
        text-align: center;
        border-style: solid;
        border-width: 3px;
        border-color: green;
        border-radius: 15px;
    }
    

app/views/tab/wand.html.haml
#wand.col-xs-12
    %span MAGIC WAND
      
// IGNORE, BUT KEEP THIS LINE (Back button)   
= render :partial => "application/back_to_root"

:scss
    #wand{
        height: 100%;
        width: 100%;
        color: white;
        font-family: Avenir, sans-serif;
        font-size: 4em;
        text-align: center;
        
        background: desaturate(orange, 80%);
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
       
    }
   